// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _feedback_t_h
#define _feedback_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define FEEDBACK_T_VAL 0
#define FEEDBACK_T_RATE 1
#define FEEDBACK_T_ACCEL 2

typedef struct _feedback_t feedback_t;
struct _feedback_t
{
    float x[3];
    float y[3];
    float z[3];
    float roll;
    float pitch;
    float yaw;
    int8_t flags;
    int64_t utime;
    float batteryVoltage;
};

/**
 * Create a deep copy of a feedback_t.
 * When no longer needed, destroy it with feedback_t_destroy()
 */
feedback_t *feedback_t_copy(const feedback_t *to_copy);

/**
 * Destroy an instance of feedback_t created by feedback_t_copy()
 */
void feedback_t_destroy(feedback_t *to_destroy);

/**
 * Encode a message of type feedback_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to feedback_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int feedback_t_encode(void *buf, int offset, int maxlen, const feedback_t *p);

/**
 * Decode a message of type feedback_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with feedback_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int feedback_t_decode(const void *buf, int offset, int maxlen, feedback_t *msg);

/**
 * Release resources allocated by feedback_t_decode()
 * @return 0
 */
int feedback_t_decode_cleanup(feedback_t *p);

/**
 * Check how many bytes are required to encode a message of type feedback_t
 */
int feedback_t_encoded_size(const feedback_t *p);

// LCM support functions. Users should not call these
int64_t __feedback_t_get_hash(void);
uint64_t __feedback_t_hash_recursive(const __lcm_hash_ptr *p);
int __feedback_t_encode_array(void *buf, int offset, int maxlen, const feedback_t *p, int elements);
int __feedback_t_decode_array(const void *buf, int offset, int maxlen, feedback_t *p, int elements);
int __feedback_t_decode_array_cleanup(feedback_t *p, int elements);
int __feedback_t_encoded_array_size(const feedback_t *p, int elements);
int __feedback_t_clone_array(const feedback_t *p, feedback_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
