#ifndef INT32_H
#define INT32_H
#define int32 int32_t
#define __int32_clone_array __int32_t_clone_array
#define __int32_decode_array_cleanup __int32_t_decode_array_cleanup
#define __int32_decode_array __int32_t_decode_array
#define __int32_encoded_array_size __int32_t_encoded_array_size
#define __int32_encode_array __int32_t_encode_array
#define __int32_hash_recursive __int32_t_hash_recursive

#endif
