// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _raw_pose_t_h
#define _raw_pose_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _raw_pose_t raw_pose_t;
struct _raw_pose_t
{
    float      x;
    float      y;
    float      yaw;
    int64_t    utime;
};

/**
 * Create a deep copy of a raw_pose_t.
 * When no longer needed, destroy it with raw_pose_t_destroy()
 */
raw_pose_t* raw_pose_t_copy(const raw_pose_t* to_copy);

/**
 * Destroy an instance of raw_pose_t created by raw_pose_t_copy()
 */
void raw_pose_t_destroy(raw_pose_t* to_destroy);

/**
 * Encode a message of type raw_pose_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to raw_pose_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int raw_pose_t_encode(void *buf, int offset, int maxlen, const raw_pose_t *p);

/**
 * Decode a message of type raw_pose_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with raw_pose_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int raw_pose_t_decode(const void *buf, int offset, int maxlen, raw_pose_t *msg);

/**
 * Release resources allocated by raw_pose_t_decode()
 * @return 0
 */
int raw_pose_t_decode_cleanup(raw_pose_t *p);

/**
 * Check how many bytes are required to encode a message of type raw_pose_t
 */
int raw_pose_t_encoded_size(const raw_pose_t *p);

// LCM support functions. Users should not call these
int64_t __raw_pose_t_get_hash(void);
int64_t __raw_pose_t_hash_recursive(const __lcm_hash_ptr *p);
int     __raw_pose_t_encode_array(void *buf, int offset, int maxlen, const raw_pose_t *p, int elements);
int     __raw_pose_t_decode_array(const void *buf, int offset, int maxlen, raw_pose_t *p, int elements);
int     __raw_pose_t_decode_array_cleanup(raw_pose_t *p, int elements);
int     __raw_pose_t_encoded_array_size(const raw_pose_t *p, int elements);
int     __raw_pose_t_clone_array(const raw_pose_t *p, raw_pose_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
