// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _setpt_t_h
#define _setpt_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define SETPT_T_POSE 0
#define SETPT_T_TAKEOFF 1
#define SETPT_T_LAND 2
#define SETPT_T_IDLE 3
#define SETPT_T_RATE 4

typedef struct _setpt_t setpt_t;
struct _setpt_t
{
    float      x;
    float      y;
    float      z;
    float      yaw;
    int8_t     flags;
    int32_t    utime;
};

/**
 * Create a deep copy of a setpt_t.
 * When no longer needed, destroy it with setpt_t_destroy()
 */
setpt_t* setpt_t_copy(const setpt_t* to_copy);

/**
 * Destroy an instance of setpt_t created by setpt_t_copy()
 */
void setpt_t_destroy(setpt_t* to_destroy);

/**
 * Encode a message of type setpt_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to setpt_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int setpt_t_encode(void *buf, int offset, int maxlen, const setpt_t *p);

/**
 * Decode a message of type setpt_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with setpt_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int setpt_t_decode(const void *buf, int offset, int maxlen, setpt_t *msg);

/**
 * Release resources allocated by setpt_t_decode()
 * @return 0
 */
int setpt_t_decode_cleanup(setpt_t *p);

/**
 * Check how many bytes are required to encode a message of type setpt_t
 */
int setpt_t_encoded_size(const setpt_t *p);

// LCM support functions. Users should not call these
int64_t __setpt_t_get_hash(void);
int64_t __setpt_t_hash_recursive(const __lcm_hash_ptr *p);
int     __setpt_t_encode_array(void *buf, int offset, int maxlen, const setpt_t *p, int elements);
int     __setpt_t_decode_array(const void *buf, int offset, int maxlen, setpt_t *p, int elements);
int     __setpt_t_decode_array_cleanup(setpt_t *p, int elements);
int     __setpt_t_encoded_array_size(const setpt_t *p, int elements);
int     __setpt_t_clone_array(const setpt_t *p, setpt_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
