// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <lcm/lcm_coretypes.h>
#include <stdint.h>
#include <stdlib.h>

#ifndef _dji_t_h
#define _dji_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _dji_t dji_t;
struct _dji_t
{
    float roll;
    float pitch;
    float yaw;
    float thrust;
};

/**
 * Create a deep copy of a dji_t.
 * When no longer needed, destroy it with dji_t_destroy()
 */
dji_t *dji_t_copy(const dji_t *to_copy);

/**
 * Destroy an instance of dji_t created by dji_t_copy()
 */
void dji_t_destroy(dji_t *to_destroy);

/**
 * Encode a message of type dji_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to dji_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int dji_t_encode(void *buf, int offset, int maxlen, const dji_t *p);

/**
 * Decode a message of type dji_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with dji_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int dji_t_decode(const void *buf, int offset, int maxlen, dji_t *msg);

/**
 * Release resources allocated by dji_t_decode()
 * @return 0
 */
int dji_t_decode_cleanup(dji_t *p);

/**
 * Check how many bytes are required to encode a message of type dji_t
 */
int dji_t_encoded_size(const dji_t *p);

// LCM support functions. Users should not call these
int64_t __dji_t_get_hash(void);
uint64_t __dji_t_hash_recursive(const __lcm_hash_ptr *p);
int __dji_t_encode_array(void *buf, int offset, int maxlen, const dji_t *p, int elements);
int __dji_t_decode_array(const void *buf, int offset, int maxlen, dji_t *p, int elements);
int __dji_t_decode_array_cleanup(dji_t *p, int elements);
int __dji_t_encoded_array_size(const dji_t *p, int elements);
int __dji_t_clone_array(const dji_t *p, dji_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
