// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <lcm/lcm_coretypes.h>
#include <stdint.h>
#include <stdlib.h>

#ifndef _imu_t_h
#define _imu_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _imu_t imu_t;
struct _imu_t
{
    float refYaw;
    float gAccX;
    float gAccY;
    float gAccZ;
    float AccX;
    float AccY;
    float AccZ;
    float AngRateX;
    float AngRateY;
    float AngRateZ;
    float MagX;
    float MagY;
    float MagZ;
    float M[9];
    int64_t time;
    int32_t Timer;
    float GyroBiasX;
    float GyroBiasY;
    float GyroBiasZ;
    float AccBiasX;
    float AccBiasY;
    float AccBiasZ;
};

/**
 * Create a deep copy of a imu_t.
 * When no longer needed, destroy it with imu_t_destroy()
 */
imu_t *imu_t_copy(const imu_t *to_copy);

/**
 * Destroy an instance of imu_t created by imu_t_copy()
 */
void imu_t_destroy(imu_t *to_destroy);

/**
 * Encode a message of type imu_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to imu_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int imu_t_encode(void *buf, int offset, int maxlen, const imu_t *p);

/**
 * Decode a message of type imu_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with imu_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int imu_t_decode(const void *buf, int offset, int maxlen, imu_t *msg);

/**
 * Release resources allocated by imu_t_decode()
 * @return 0
 */
int imu_t_decode_cleanup(imu_t *p);

/**
 * Check how many bytes are required to encode a message of type imu_t
 */
int imu_t_encoded_size(const imu_t *p);

// LCM support functions. Users should not call these
int64_t __imu_t_get_hash(void);
uint64_t __imu_t_hash_recursive(const __lcm_hash_ptr *p);
int __imu_t_encode_array(void *buf, int offset, int maxlen, const imu_t *p, int elements);
int __imu_t_decode_array(const void *buf, int offset, int maxlen, imu_t *p, int elements);
int __imu_t_decode_array_cleanup(imu_t *p, int elements);
int __imu_t_encoded_array_size(const imu_t *p, int elements);
int __imu_t_clone_array(const imu_t *p, imu_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
