// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <lcm/lcm_coretypes.h>
#include <stdint.h>
#include <stdlib.h>

#ifndef _lidar_t_h
#define _lidar_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lidar_t lidar_t;
struct _lidar_t
{
    float dist;
    float vel;
    int64_t time;
};

/**
 * Create a deep copy of a lidar_t.
 * When no longer needed, destroy it with lidar_t_destroy()
 */
lidar_t *lidar_t_copy(const lidar_t *to_copy);

/**
 * Destroy an instance of lidar_t created by lidar_t_copy()
 */
void lidar_t_destroy(lidar_t *to_destroy);

/**
 * Encode a message of type lidar_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to lidar_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int lidar_t_encode(void *buf, int offset, int maxlen, const lidar_t *p);

/**
 * Decode a message of type lidar_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with lidar_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int lidar_t_decode(const void *buf, int offset, int maxlen, lidar_t *msg);

/**
 * Release resources allocated by lidar_t_decode()
 * @return 0
 */
int lidar_t_decode_cleanup(lidar_t *p);

/**
 * Check how many bytes are required to encode a message of type lidar_t
 */
int lidar_t_encoded_size(const lidar_t *p);

// LCM support functions. Users should not call these
int64_t __lidar_t_get_hash(void);
uint64_t __lidar_t_hash_recursive(const __lcm_hash_ptr *p);
int __lidar_t_encode_array(void *buf, int offset, int maxlen, const lidar_t *p, int elements);
int __lidar_t_decode_array(const void *buf, int offset, int maxlen, lidar_t *p, int elements);
int __lidar_t_decode_array_cleanup(lidar_t *p, int elements);
int __lidar_t_encoded_array_size(const lidar_t *p, int elements);
int __lidar_t_clone_array(const lidar_t *p, lidar_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
