/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __laser_t_hpp__
#define __laser_t_hpp__

#include <vector>


class laser_t
{
    public:
        int64_t    utime;

        int32_t    nranges;

        std::vector< float > ranges;

        int32_t    nintensities;

        std::vector< float > intensities;

        float      rad0;

        float      radstep;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~laser_t() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "laser_t"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr *p);
};

int laser_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int laser_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int laser_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t laser_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* laser_t::getTypeName()
{
    return "laser_t";
}

int laser_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->nranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->nranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nintensities, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->nintensities > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->nintensities);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->rad0, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->radstep, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int laser_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->nranges > 0) {
        this->ranges.resize(this->nranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->nranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nintensities, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->nintensities > 0) {
        this->intensities.resize(this->nintensities);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->nintensities);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->rad0, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->radstep, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int laser_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->nranges);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->nintensities);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t laser_t::_computeHash(const __zcm_hash_ptr *)
{
    uint64_t hash = (uint64_t)0x64ffa193fe6124e0LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
