/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __test_t_hpp__
#define __test_t_hpp__

#include <string>


class test_t
{
    public:
        std::string letter;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~test_t() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "test_t"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr *p);
};

int test_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int test_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int test_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t test_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* test_t::getTypeName()
{
    return "test_t";
}

int test_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* letter_cstr = (char*) this->letter.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &letter_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int test_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __letter_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__letter_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__letter_len__ > maxlen - pos) return -1;
    this->letter.assign(((const char*)buf) + offset + pos, __letter_len__ - 1);
    pos += __letter_len__;

    return pos;
}

int test_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->letter.size() + 4 + 1;
    return enc_size;
}

uint64_t test_t::_computeHash(const __zcm_hash_ptr *)
{
    uint64_t hash = (uint64_t)0xf6805d3d506029beLL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
