/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __tracked_state_t_hpp__
#define __tracked_state_t_hpp__



class tracked_state_t
{
    public:
        int64_t    utime;

        double     state[13];

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t   X = 0;
        static constexpr int8_t   Y = 1;
        static constexpr int8_t   Z = 2;
        static constexpr int8_t   Q0 = 3;
        static constexpr int8_t   Q1 = 4;
        static constexpr int8_t   Q2 = 5;
        static constexpr int8_t   Q3 = 6;
        static constexpr int8_t   XDOT = 7;
        static constexpr int8_t   YDOT = 8;
        static constexpr int8_t   ZDOT = 9;
        static constexpr int8_t   W_X = 10;
        static constexpr int8_t   W_Y = 11;
        static constexpr int8_t   W_Z = 12;
        #else
        static const     int8_t   X = 0;
        static const     int8_t   Y = 1;
        static const     int8_t   Z = 2;
        static const     int8_t   Q0 = 3;
        static const     int8_t   Q1 = 4;
        static const     int8_t   Q2 = 5;
        static const     int8_t   Q3 = 6;
        static const     int8_t   XDOT = 7;
        static const     int8_t   YDOT = 8;
        static const     int8_t   ZDOT = 9;
        static const     int8_t   W_X = 10;
        static const     int8_t   W_Y = 11;
        static const     int8_t   W_Z = 12;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~tracked_state_t() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "tracked_state_t"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr *p);
};

int tracked_state_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int tracked_state_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int tracked_state_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t tracked_state_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* tracked_state_t::getTypeName()
{
    return "tracked_state_t";
}

int tracked_state_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->state[0], 13);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int tracked_state_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->state[0], 13);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int tracked_state_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 13);
    return enc_size;
}

uint64_t tracked_state_t::_computeHash(const __zcm_hash_ptr *)
{
    uint64_t hash = (uint64_t)0x243ef7f095b40261LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
