// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "tanfan/nav/msg/feedback_t.h"

static int __feedback_t_hash_computed;
static uint64_t __feedback_t_hash;

uint64_t __feedback_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __feedback_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__feedback_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x053e73d54f9225d9LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __feedback_t_get_hash(void)
{
    if (!__feedback_t_hash_computed) {
        __feedback_t_hash = (int64_t)__feedback_t_hash_recursive(NULL);
        __feedback_t_hash_computed = 1;
    }

    return __feedback_t_hash;
}

int __feedback_t_encode_array(void *buf, int offset, int maxlen, const feedback_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].x, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].y, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].z, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].flags), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].batteryVoltage), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int feedback_t_encode(void *buf, int offset, int maxlen, const feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __feedback_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __feedback_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __feedback_t_encoded_array_size(const feedback_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].x, 3);

        size += __float_encoded_array_size(p[element].y, 3);

        size += __float_encoded_array_size(p[element].z, 3);

        size += __float_encoded_array_size(&(p[element].roll), 1);

        size += __float_encoded_array_size(&(p[element].pitch), 1);

        size += __float_encoded_array_size(&(p[element].yaw), 1);

        size += __int8_t_encoded_array_size(&(p[element].flags), 1);

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __float_encoded_array_size(&(p[element].batteryVoltage), 1);

    }
    return size;
}

int feedback_t_encoded_size(const feedback_t *p)
{
    return 8 + __feedback_t_encoded_array_size(p, 1);
}

int __feedback_t_decode_array(const void *buf, int offset, int maxlen, feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].x, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].y, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].z, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].flags), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].batteryVoltage), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __feedback_t_decode_array_cleanup(feedback_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].x, 3);

        __float_decode_array_cleanup(p[element].y, 3);

        __float_decode_array_cleanup(p[element].z, 3);

        __float_decode_array_cleanup(&(p[element].roll), 1);

        __float_decode_array_cleanup(&(p[element].pitch), 1);

        __float_decode_array_cleanup(&(p[element].yaw), 1);

        __int8_t_decode_array_cleanup(&(p[element].flags), 1);

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __float_decode_array_cleanup(&(p[element].batteryVoltage), 1);

    }
    return 0;
}

int feedback_t_decode(const void *buf, int offset, int maxlen, feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __feedback_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __feedback_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int feedback_t_decode_cleanup(feedback_t *p)
{
    return __feedback_t_decode_array_cleanup(p, 1);
}

int __feedback_t_clone_array(const feedback_t *p, feedback_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].x, q[element].x, 3);

        __float_clone_array(p[element].y, q[element].y, 3);

        __float_clone_array(p[element].z, q[element].z, 3);

        __float_clone_array(&(p[element].roll), &(q[element].roll), 1);

        __float_clone_array(&(p[element].pitch), &(q[element].pitch), 1);

        __float_clone_array(&(p[element].yaw), &(q[element].yaw), 1);

        __int8_t_clone_array(&(p[element].flags), &(q[element].flags), 1);

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __float_clone_array(&(p[element].batteryVoltage), &(q[element].batteryVoltage), 1);

    }
    return 0;
}

feedback_t *feedback_t_copy(const feedback_t *p)
{
    feedback_t *q = (feedback_t*) malloc(sizeof(feedback_t));
    __feedback_t_clone_array(p, q, 1);
    return q;
}

void feedback_t_destroy(feedback_t *p)
{
    __feedback_t_decode_array_cleanup(p, 1);
    free(p);
}

