// clang-format off
/**
 * 	AUTOGENERATED FILE!! DO NOT EDIT!!!!
 */


#include "DataDict.hpp"
#include "AbstractData.hpp"

void DataDict::initializeDictionary_generated()
{
	dict["STATE_attitude"] = std::shared_ptr<AbstractData>(new AbstractData(4, {"attitude_w", "attitude_x", "attitude_y", "attitude_z"}));
	dict["STATE_acceleration"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"acc_x", "acc_y", "acc_z"}));
	dict["STATE_gyro_biases"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"gbias_x", "gbias_y", "gbias_z"}));
	dict["STATE_covariance"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"covariance_matrix"}));
	dict["STATE_angular_velocity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"ω_x", "ω_y", "ω_z"}));
	dict["STATE_magnetic_field"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"mag_x", "mag_y", "mag_z"}));
	dict["STATE_position"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"pos_x", "pos_y", "pos_z"}));
	dict["STATE_gravity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"grav_x", "grav_y", "grav_z"}));
	dict["STATE_velocity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"vel_x", "vel_y", "vel_z"}));
	dict["STATE_accel_biases"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"abias_x", "abias_y", "abias_z"}));
	dict["SIM_STATE_attitude"] = std::shared_ptr<AbstractData>(new AbstractData(4, {"attitude_w", "attitude_x", "attitude_y", "attitude_z"}));
	dict["SIM_STATE_acceleration"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"acc_x", "acc_y", "acc_z"}));
	dict["SIM_STATE_gyro_biases"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"gbias_x", "gbias_y", "gbias_z"}));
	dict["SIM_STATE_covariance"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"covariance_matrix"}));
	dict["SIM_STATE_angular_velocity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"ω_x", "ω_y", "ω_z"}));
	dict["SIM_STATE_magnetic_field"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"mag_x", "mag_y", "mag_z"}));
	dict["SIM_STATE_position"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"pos_x", "pos_y", "pos_z"}));
	dict["SIM_STATE_gravity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"grav_x", "grav_y", "grav_z"}));
	dict["SIM_STATE_velocity"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"vel_x", "vel_y", "vel_z"}));
	dict["SIM_STATE_accel_biases"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"abias_x", "abias_y", "abias_z"}));
	dict["HEIGHT_LIDAR_distance"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"distance_x"}));
	dict["IMU_magnetometer"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"magnetometer_x", "magnetometer_y", "magnetometer_z"}));
	dict["IMU_angular_rates"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"angular_rates_x", "angular_rates_y", "angular_rates_z"}));
	dict["IMU_acceleration"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"acceleration_x", "acceleration_y", "acceleration_z"}));
	dict["GLOBAL_UPDATE_position"] = std::shared_ptr<AbstractData>(new AbstractData(3, {"position_x", "position_y", "position_z"}));
	dict["GLOBAL_UPDATE_attitude"] = std::shared_ptr<AbstractData>(new AbstractData(4, {"attitude_w", "attitude_x", "attitude_y", "attitude_z"}));
	dict["PLANE_FIT_z"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"z_x"}));
	dict["PLANE_FIT_roll"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"roll_x"}));
	dict["PLANE_FIT_z_dot"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"z_dot_x"}));
	dict["PLANE_FIT_pitch"] = std::shared_ptr<AbstractData>(new AbstractData(1, {"pitch_x"}));
}
