// clang-format off
/**
 * 	AUTOGENERATED FILE!! DO NOT EDIT!!!!
 */


#include "ui_ListWindow.h"
#include "ListWindow.h"

void ListWindow::addChannels_generated()
{
	new ChannelListItem("STATE_attitude", "STATE_attitude:quaternion_t", list_);
	new ChannelListItem("STATE_acceleration", "STATE_acceleration:vector3_t", list_);
	new ChannelListItem("STATE_gyro_biases", "STATE_gyro_biases:vector3_t", list_);
	new ChannelListItem("STATE_covariance", "STATE_covariance:matrix_t", list_);
	new ChannelListItem("STATE_angular_velocity", "STATE_angular_velocity:vector3_t", list_);
	new ChannelListItem("STATE_magnetic_field", "STATE_magnetic_field:vector3_t", list_);
	new ChannelListItem("STATE_position", "STATE_position:vector3_t", list_);
	new ChannelListItem("STATE_gravity", "STATE_gravity:vector3_t", list_);
	new ChannelListItem("STATE_velocity", "STATE_velocity:vector3_t", list_);
	new ChannelListItem("STATE_accel_biases", "STATE_accel_biases:vector3_t", list_);
	new ChannelListItem("SIM_STATE_attitude", "SIM_STATE_attitude:quaternion_t", list_);
	new ChannelListItem("SIM_STATE_acceleration", "SIM_STATE_acceleration:vector3_t", list_);
	new ChannelListItem("SIM_STATE_gyro_biases", "SIM_STATE_gyro_biases:vector3_t", list_);
	new ChannelListItem("SIM_STATE_covariance", "SIM_STATE_covariance:matrix_t", list_);
	new ChannelListItem("SIM_STATE_angular_velocity", "SIM_STATE_angular_velocity:vector3_t", list_);
	new ChannelListItem("SIM_STATE_magnetic_field", "SIM_STATE_magnetic_field:vector3_t", list_);
	new ChannelListItem("SIM_STATE_position", "SIM_STATE_position:vector3_t", list_);
	new ChannelListItem("SIM_STATE_gravity", "SIM_STATE_gravity:vector3_t", list_);
	new ChannelListItem("SIM_STATE_velocity", "SIM_STATE_velocity:vector3_t", list_);
	new ChannelListItem("SIM_STATE_accel_biases", "SIM_STATE_accel_biases:vector3_t", list_);
	new ChannelListItem("HEIGHT_LIDAR_distance", "HEIGHT_LIDAR_distance:vector1_t", list_);
	new ChannelListItem("IMU_magnetometer", "IMU_magnetometer:vector3_t", list_);
	new ChannelListItem("IMU_angular_rates", "IMU_angular_rates:vector3_t", list_);
	new ChannelListItem("IMU_acceleration", "IMU_acceleration:vector3_t", list_);
	new ChannelListItem("GLOBAL_UPDATE_position", "GLOBAL_UPDATE_position:vector3_t", list_);
	new ChannelListItem("GLOBAL_UPDATE_attitude", "GLOBAL_UPDATE_attitude:quaternion_t", list_);
	new ChannelListItem("PLANE_FIT_z", "PLANE_FIT_z:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_roll", "PLANE_FIT_roll:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_z_dot", "PLANE_FIT_z_dot:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_pitch", "PLANE_FIT_pitch:vector1_t", list_);
}
