// clang-format off
/**
 * 	AUTOGENERATED FILE!! DO NOT EDIT!!!!
 */


#include "ui_ListWindow.h"
#include "ListWindow.h"

void ListWindow::addChannels_generated()
{
	new ChannelListItem("PID_ERROR_pos_error", "PID_ERROR_pos_error:vector3_t", list_);
	new ChannelListItem("PID_ERROR_vel_error", "PID_ERROR_vel_error:vector3_t", list_);
	new ChannelListItem("PID_ERROR_thrust", "PID_ERROR_thrust:vector1_t", list_);
	new ChannelListItem("PID_ERROR_yaw_error", "PID_ERROR_yaw_error:vector1_t", list_);
	new ChannelListItem("PID_ERROR_pitch", "PID_ERROR_pitch:vector1_t", list_);
	new ChannelListItem("PID_ERROR_roll", "PID_ERROR_roll:vector1_t", list_);
	new ChannelListItem("SIM_IMU_acceleration", "SIM_IMU_acceleration:vector3_t", list_);
	new ChannelListItem("SIM_IMU_angular_rates", "SIM_IMU_angular_rates:vector3_t", list_);
	new ChannelListItem("SIM_IMU_magnetometer", "SIM_IMU_magnetometer:vector3_t", list_);
	new ChannelListItem("GT_SLAMDRIFT_attitude_drift", "GT_SLAMDRIFT_attitude_drift:quaternion_t", list_);
	new ChannelListItem("GT_SLAMDRIFT_position_drift", "GT_SLAMDRIFT_position_drift:vector3_t", list_);
	new ChannelListItem("GT_WORLD_gravity", "GT_WORLD_gravity:vector3_t", list_);
	new ChannelListItem("GT_WORLD_magnetic_field", "GT_WORLD_magnetic_field:vector3_t", list_);
	new ChannelListItem("IMU_acceleration", "IMU_acceleration:vector3_t", list_);
	new ChannelListItem("IMU_angular_rates", "IMU_angular_rates:vector3_t", list_);
	new ChannelListItem("IMU_magnetometer", "IMU_magnetometer:vector3_t", list_);
	new ChannelListItem("HEIGHT_LIDAR_distance", "HEIGHT_LIDAR_distance:vector1_t", list_);
	new ChannelListItem("GLOBAL_UPDATE_position", "GLOBAL_UPDATE_position:vector3_t", list_);
	new ChannelListItem("GLOBAL_UPDATE_attitude", "GLOBAL_UPDATE_attitude:quaternion_t", list_);
	new ChannelListItem("STATE_attitude", "STATE_attitude:quaternion_t", list_);
	new ChannelListItem("STATE_accel_biases", "STATE_accel_biases:vector3_t", list_);
	new ChannelListItem("STATE_velocity", "STATE_velocity:vector3_t", list_);
	new ChannelListItem("STATE_angular_velocity", "STATE_angular_velocity:vector3_t", list_);
	new ChannelListItem("STATE_gravity", "STATE_gravity:vector3_t", list_);
	new ChannelListItem("STATE_position", "STATE_position:vector3_t", list_);
	new ChannelListItem("STATE_gyro_biases", "STATE_gyro_biases:vector3_t", list_);
	new ChannelListItem("STATE_acceleration", "STATE_acceleration:vector3_t", list_);
	new ChannelListItem("STATE_covariance", "STATE_covariance:matrix_t", list_);
	new ChannelListItem("STATE_magnetic_field", "STATE_magnetic_field:vector3_t", list_);
	new ChannelListItem("PLANE_FIT_pitch", "PLANE_FIT_pitch:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_z_dot", "PLANE_FIT_z_dot:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_z", "PLANE_FIT_z:vector1_t", list_);
	new ChannelListItem("PLANE_FIT_roll", "PLANE_FIT_roll:vector1_t", list_);
	new ChannelListItem("GT_INERTIAL_attitude", "GT_INERTIAL_attitude:quaternion_t", list_);
	new ChannelListItem("GT_INERTIAL_position", "GT_INERTIAL_position:vector3_t", list_);
	new ChannelListItem("GT_INERTIAL_velocity", "GT_INERTIAL_velocity:vector3_t", list_);
	new ChannelListItem("GT_INERTIAL_angular_velocity", "GT_INERTIAL_angular_velocity:vector3_t", list_);
	new ChannelListItem("GT_INERTIAL_acceleration", "GT_INERTIAL_acceleration:vector3_t", list_);
	new ChannelListItem("GT_IMU_accel_bias", "GT_IMU_accel_bias:vector3_t", list_);
	new ChannelListItem("GT_IMU_gyro_bias", "GT_IMU_gyro_bias:vector3_t", list_);
}
